services:
  db:
    image: postgres:latest
    container_name: mp_game_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: game
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

